project:
  type: website
  output-dir: docs

website:
  title: "Instituto de Genetica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    toc-title: Contents

editor: visual

