project:
  type: website
  output-dir: docs

website:
  title: "Centro de Registro y Vigilancia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-title: Contents

editor: visual

